server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5432/FileUpload
    username: postgres
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  app:
    cors:
      allowed-origins: http://localhost:3000